.\" +----------
.\" |
.\" |			       GITKEYS man page
.\" |
.\" |	       Copyright 1993-1999, 2006-2007 Free Software Foundation, Inc.
.\" |
.\" |	This file is part of GNUIT (GNU Interactive Tools)
.\" |
.\" |	GNUIT is free software; you can redistribute it and/or modify it under
.\" | the terms of the GNU General Public License as published by the Free
.\" | Software Foundation; either version 3, or (at your option) any later
.\" | version.
.\" |
.\" | GNUIT is distributed in the hope that it will be useful, but WITHOUT ANY
.\" | WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
.\" | FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
.\" | details.
.\" |
.\" | You should have received a copy of the GNU General Public License along
.\" | with GNUIT; see the file COPYING. If not, see http://www.gnu.org/licenses/
.\" |
.TH gitkeys 1
.SH NAME
gitkeys \- GNU Interactive Tools - Display key sequence utility
.SH SYNTAX
.I gitkeys

.SH DESCRIPTION
.I gitkeys
is a program that displays the key sequence sent by the pressed
key. This is the key sequence received by GNUIT tools, so this program
is useful when setting up the .gitrc.TERM configuration files.


.SH BUGS

Please send bug reports to:
.br
.I Ian Beckwith <ianb@erislabs.net>

.SH SEE ALSO
gitfm(1) gitps(1) gitview(1) gitmount(1) gitaction(1) gitrgrep(1) gitunpack(1)

.SH AUTHORS
.I Tudor Hulubei <tudor@cs.unh.edu>
.br
.I Andrei Pitis <pink@pub.ro>
.br
.I Ian Beckwith <ianb@erislabs.net> (Current maintainer)
