options(repos = structure(c(CRAN = "https://cran.rstudio.com/")))

install.packages("readr")
install.packages("psych")
install.packages("e1071")
install.packages("tidyverse")
install.packages("dplyr")
install.packages("caret")
install.packages("klaR")
install.packages("kernlab")
install.packages("gbm")
install.packages("mlr3")
install.packages("mlr3verse")
install.packages("pheatmap")
install.packages("kknn")
install.packages("glmnet")
install.packages("Hmisc")
install.packages("devtools")
install.packages("BiocManager")
BiocManager::install(version='3.18')
BiocManager::install("Rgraphviz")
